version: '3.7'
services:
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "7876:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.ru"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin4_data:/var/lib/pgadmin4/data
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
  postgres:
    container_name: postgres
    networks:
      - localnet
    image: library/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: "coolsite"
    ports:
      - "5432:5432"
    restart: unless-stopped
  zookeeper:
    container_name: zookeeper
    networks:
      - localnet
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    networks:
      - localnet
    image: wurstmeister/kafka
    hostname: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9094,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://kafka1:9094,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - kafka_data:/var/run/docker.sock
  minio-service:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/var/lib/s3/data
volumes:
  postgres_data:
    name: django_postgres_data
    driver: local
  kafka_data:
    name: route_kafka_data
    driver: local
  s3_data:
    name: s3_data
    driver: local
  pgadmin4_data:
    name: pgadmin4
    driver: local

networks:
  localnet:
    attachable: true
